# Netlify config to proxy API requests to your backend
# Replace https://YOUR-BACKEND-URL with your deployed backend base URL (no trailing slash)

[build]
  publish = "."  # static site root

# Example: if your backend is https://campusnav-api.onrender.com
# then /api/* on the frontend will be forwarded there
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR-BACKEND-URL/api/:splat"
#   status = 200
#   force = true

# Security headers (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
